const mongoose = require("mongoose");
const User = require("../models/User");
const Class = require("../models/Class");
const Subject = require("../models/Subject");
const School = require("../models/School");
const Attendance = require("../models/Attendance");
const ChatGroup = require("../models/ChatGroup");
const GroupMessage = require("../models/GroupMessage");
const TeacherLeave = require("../models/TeacherLeave");
const Appointment = require("../models/Appointment");
const Timetable = require("../models/Timetable");

const validId = (id) => mongoose.isValidObjectId(id);
const minutes = (time) => { const [h, m] = String(time).split(":").map(Number); return Number.isInteger(h) && Number.isInteger(m) && h >= 0 && h < 24 && m >= 0 && m < 60 ? h * 60 + m : null; };
const timeOf = (n) => `${String(Math.floor(n / 60)).padStart(2, "0")}:${String(n % 60).padStart(2, "0")}`;
const schoolUser = async (id) => User.findById(id).select("role schoolName requestedSchool name classId");

exports.createGroup = async (req, res) => {
  try {
    const { name = "Group Chat", memberIds = [] } = req.body;
    if (!req.user.schoolName || !Array.isArray(memberIds) || !memberIds.length) return res.status(400).json({ message: "Choose at least one assigned student" });
    const unique = [...new Set(memberIds.map(String))];
    if (unique.some(id => !validId(id))) return res.status(400).json({ message: "Invalid student selection" });
    const assigned = await Class.find({ teacher: req.user.id, schoolName: req.user.schoolName, students: { $in: unique } });
    const allowed = new Set(assigned.flatMap(c => c.students.map(String)));
    if (unique.some(id => !allowed.has(id))) return res.status(403).json({ message: "Groups may only include students assigned to you" });
    const students = await User.countDocuments({ _id: { $in: unique }, role: "student", schoolName: req.user.schoolName });
    if (students !== unique.length) return res.status(400).json({ message: "One or more students are unavailable" });
    const group = await ChatGroup.create({ name: String(name).trim() || "Group Chat", createdBy: req.user.id, teacher: req.user.id, schoolName: req.user.schoolName, members: [req.user.id, ...unique] });
    res.status(201).json(await group.populate("members", "name email role avatar"));
  } catch (error) { res.status(500).json({ message: "Could not create group" }); }
};
exports.getGroups = async (req, res) => {
  try { res.json(await ChatGroup.find({ schoolName: req.user.schoolName, members: req.user.id }).populate("members", "name email role avatar").sort({ lastMessageAt: -1, updatedAt: -1 })); }
  catch { res.status(500).json({ message: "Could not load groups" }); }
};
exports.getGroupMessages = async (req, res) => {
  try { const group = await ChatGroup.findOne({ _id: req.params.id, schoolName: req.user.schoolName, members: req.user.id }); if (!group) return res.status(404).json({ message: "Group not found" }); res.json(await GroupMessage.find({ group: group._id }).populate("sender", "name avatar role").sort({ createdAt: 1 }).limit(200)); }
  catch { res.status(400).json({ message: "Invalid group" }); }
};
exports.sendGroupMessage = async (req, res) => {
  try { const group = await ChatGroup.findOne({ _id: req.params.id, schoolName: req.user.schoolName, members: req.user.id }); const content = String(req.body.content || "").trim(); if (!group) return res.status(404).json({ message: "Group not found" }); if (!content) return res.status(400).json({ message: "Message cannot be empty" }); const message = await GroupMessage.create({ group: group._id, sender: req.user.id, content }); group.lastMessage = content; group.lastMessageAt = message.createdAt; await group.save(); const payload = await message.populate("sender", "name avatar role"); const io = req.app.get("io"); if (io) group.members.forEach(member => io.to(member.toString()).emit("group:new-message", payload)); res.status(201).json(payload); }
  catch { res.status(400).json({ message: "Could not send message" }); }
};

exports.createLeave = async (req, res) => { try { const { startDate, endDate, reason = "" } = req.body; const start = new Date(startDate); const end = endDate ? new Date(endDate) : start; if (Number.isNaN(+start) || Number.isNaN(+end) || end < start) return res.status(400).json({ message: "Provide a valid leave date range" }); const leave = await TeacherLeave.create({ teacher: req.user.id, schoolName: req.user.schoolName, startDate: start, endDate: end, reason }); res.status(201).json(leave); } catch { res.status(500).json({ message: "Could not submit leave request" }); } };
exports.getLeaves = async (req, res) => { try { const query = req.user.role === "teacher" ? { teacher: req.user.id } : { schoolName: req.user.schoolName }; res.json(await TeacherLeave.find(query).populate("teacher", "name email").populate("reviewedBy", "name").sort({ startDate: -1 })); } catch { res.status(500).json({ message: "Could not load leave requests" }); } };
exports.reviewLeave = async (req, res) => { try { const status = req.body.status; if (!["Approved", "Rejected", "Cancelled"].includes(status)) return res.status(400).json({ message: "Invalid leave status" }); const leave = await TeacherLeave.findOne({ _id: req.params.id, schoolName: req.user.schoolName }); if (!leave) return res.status(404).json({ message: "Leave request not found" }); if (leave.status !== "Pending") return res.status(400).json({ message: "Only pending leave requests can be reviewed" }); leave.status = status; leave.reviewedBy = req.user.id; await leave.save(); res.json(leave); } catch { res.status(400).json({ message: "Could not update leave request" }); } };
exports.getActiveLeaves = async (req, res) => { try { const today = new Date(); today.setHours(0,0,0,0); res.json(await TeacherLeave.find({ schoolName: req.user.schoolName, status: "Approved", startDate: { $lte: today }, endDate: { $gte: today } }).populate("teacher", "name email").sort({ startDate: 1 }).select("teacher startDate endDate status")); } catch { res.status(500).json({ message: "Could not load active leaves" }); } };

exports.createAppointment = async (req, res) => { try { const { schoolName, date, time, notes = "" } = req.body; if (!schoolName || !date || !time) return res.status(400).json({ message: "School, date and time are required" }); const school = await School.findOne({ normalizedName: String(schoolName).trim().toLowerCase().replace(/\s+/g, " ") }); if (!school || !school.teacherAppointmentBooking) return res.status(403).json({ message: "Teacher appointment booking is not enabled for this school" }); const dateValue = new Date(date); if (Number.isNaN(+dateValue) || dateValue < new Date(new Date().setHours(0,0,0,0))) return res.status(400).json({ message: "Choose a future appointment date" }); const appointment = await Appointment.create({ user: req.user.id, schoolName: school.name, date: dateValue, time, mode: school.appointmentMode || "Offline", notes }); res.status(201).json(appointment); } catch { res.status(500).json({ message: "Could not book appointment" }); } };
exports.getAppointments = async (req, res) => { try { const query = req.user.role === "admin" ? { schoolName: req.user.schoolName } : { user: req.user.id }; res.json(await Appointment.find(query).populate("user", "name email").sort({ date: 1, time: 1 })); } catch { res.status(500).json({ message: "Could not load appointments" }); } };
exports.updateAppointment = async (req, res) => { try { const { status, notes } = req.body; const appointment = await Appointment.findById(req.params.id); if (!appointment) return res.status(404).json({ message: "Appointment not found" }); if (req.user.role === "admin" && appointment.schoolName !== req.user.schoolName) return res.status(403).json({ message: "Forbidden" }); if (req.user.role !== "admin" && appointment.user.toString() !== req.user.id) return res.status(403).json({ message: "Forbidden" }); if (status && !["Pending", "Approved", "Rejected", "Completed", "Cancelled"].includes(status)) return res.status(400).json({ message: "Invalid appointment status" }); if (req.user.role !== "admin" && status && status !== "Cancelled") return res.status(403).json({ message: "You may only cancel your appointment" }); if (status) appointment.status = status; if (notes !== undefined) appointment.notes = notes; await appointment.save(); res.json(appointment); } catch { res.status(400).json({ message: "Could not update appointment" }); } };

exports.createTimetable = async (req, res) => { try { const { classId, subjectId, teacherId, day, startTime, durationMinutes } = req.body; const start = minutes(startTime), duration = Number(durationMinutes); if (!validId(classId) || !validId(subjectId) || !validId(teacherId) || start === null || !Number.isInteger(duration) || duration < 1 || duration > 600) return res.status(400).json({ message: "Provide valid timetable details" }); const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]; if (!days.includes(day)) return res.status(400).json({ message: "Invalid day" }); const [classData, subject, teacher] = await Promise.all([Class.findOne({ _id: classId, schoolName: req.user.schoolName }), Subject.findOne({ _id: subjectId, class: classId, schoolName: req.user.schoolName }), User.findOne({ _id: teacherId, role: "teacher", schoolName: req.user.schoolName })]); if (!classData || !subject || !teacher) return res.status(400).json({ message: "Class, subject and teacher must belong to your school" }); const end = start + duration; if (end > 1440) return res.status(400).json({ message: "Class cannot end after midnight" }); const entries = await Timetable.find({ schoolName: req.user.schoolName, day, $or: [{ class: classId }, { teacher: teacherId }] }); if (entries.some(item => start < minutes(item.endTime) && end > minutes(item.startTime))) return res.status(409).json({ message: "This class or teacher already has an overlapping period" }); const entry = await Timetable.create({ schoolName: req.user.schoolName, class: classId, subject: subjectId, teacher: teacherId, day, startTime: timeOf(start), endTime: timeOf(end), durationMinutes: duration }); res.status(201).json(await entry.populate(["class", "subject", "teacher"])); } catch { res.status(500).json({ message: "Could not create timetable entry" }); } };
exports.getTimetable = async (req, res) => { try { const day = req.query.day; const query = { schoolName: req.user.schoolName }; if (day) query.day = day; if (req.user.role === "teacher") query.teacher = req.user.id; if (req.user.role === "student") { const user = await schoolUser(req.user.id); if (!user.classId) return res.json([]); query.class = user.classId; } const entries = await Timetable.find(query).populate("class", "name section").populate("subject", "name").populate("teacher", "name email").sort({ startTime: 1 }); const today = new Date(); today.setHours(0,0,0,0); const attendance = await Attendance.find({ schoolName: req.user.schoolName, date: { $gte: today } }).select("teacher"); const marked = new Set(attendance.map(a => String(a.teacher))); res.json(entries.map(e => ({ ...e.toObject(), teacherAttendance: marked.has(String(e.teacher?._id || e.teacher)) ? "Present" : "Not Marked" }))); } catch { res.status(500).json({ message: "Could not load timetable" }); } };
exports.deleteTimetable = async (req, res) => { try { const result = await Timetable.deleteOne({ _id: req.params.id, schoolName: req.user.schoolName }); if (!result.deletedCount) return res.status(404).json({ message: "Timetable entry not found" }); res.json({ message: "Timetable entry deleted" }); } catch { res.status(400).json({ message: "Invalid timetable entry" }); } };
