const crypto = require("crypto");
const https = require("https");
const Payment = require("../models/Payment");
const FeePlan = require("../models/FeePlan");
const SchoolSubscription = require("../models/SchoolSubscription");
const TeacherCompensation = require("../models/TeacherCompensation");
const PaymentSettings = require("../models/PaymentSettings");
const FreePeriod = require("../models/FreePeriod");
const PaymentAuditLog = require("../models/PaymentAuditLog");
const PaymentWebhookEvent = require("../models/PaymentWebhookEvent");
const User = require("../models/User");

const fail = (res, error) => res.status(error.status || 500).json({ message: error.status === 503 ? "Payment gateway is unavailable" : (error.message || "Payment operation failed") });
const invalid = message => Object.assign(new Error(message), { status: 400 });
const same = (a, b) => { const x = Buffer.from(a || ""), y = Buffer.from(b || ""); return x.length === y.length && crypto.timingSafeEqual(x, y); };
const receipt = payment => payment.receiptNumber || `TH-${payment._id.toString().slice(-10).toUpperCase()}-${Date.now().toString().slice(-6)}`;
const addMonths = (date, months) => { const d = new Date(date); const day = d.getUTCDate(); d.setUTCDate(1); d.setUTCMonth(d.getUTCMonth() + months); const last = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + 1, 0)).getUTCDate(); d.setUTCDate(Math.min(day, last)); return d; };
const audit = (req, action, previousValue, newValue, reason = "") => PaymentAuditLog.create({ actor: req.user.id, role: req.user.role, schoolName: newValue?.schoolName || previousValue?.schoolName || req.user.schoolName || "", action, previousValue, newValue, reason });

async function settings() { let s = await PaymentSettings.findOne(); if (!s) s = await PaymentSettings.create({}); const live = s.environment === "live"; return { environment: s.environment, onlineEnabled: s.onlineEnabled, offlineEnabled: s.offlineEnabled, keyId: (live ? process.env.RAZORPAY_LIVE_KEY_ID : process.env.RAZORPAY_TEST_KEY_ID) || process.env.RAZORPAY_KEY_ID, keySecret: (live ? process.env.RAZORPAY_LIVE_KEY_SECRET : process.env.RAZORPAY_TEST_KEY_SECRET) || process.env.RAZORPAY_KEY_SECRET }; }
function gateway(method, path, body, c) { return new Promise((resolve, reject) => { if (!c.keyId || !c.keySecret) return reject(Object.assign(new Error("Razorpay is not configured"), { status: 503 })); const payload = body ? JSON.stringify(body) : ""; const request = https.request({ hostname: "api.razorpay.com", path, method, headers: { Authorization: `Basic ${Buffer.from(`${c.keyId}:${c.keySecret}`).toString("base64")}`, "Content-Type": "application/json", ...(payload && { "Content-Length": Buffer.byteLength(payload) }) } }, response => { let data = ""; response.on("data", c => data += c); response.on("end", () => { try { const json = JSON.parse(data || "{}"); if (response.statusCode >= 200 && response.statusCode < 300) resolve(json); else reject(Object.assign(new Error(json.error?.description || "Razorpay request failed"), { status: response.statusCode })); } catch (_) { reject(new Error("Invalid payment gateway response")); } }); }); request.on("error", reject); if (payload) request.write(payload); request.end(); }); }
const schoolAdmin = schoolName => User.findOne({ role: "admin", schoolName }).select("_id");
const superAdmin = () => User.findOne({ role: "superadmin" }).select("_id");
async function activeFreePeriod(schoolName, start, end) { return FreePeriod.findOne({ schoolName, status: "Active", startDate: { $lte: end }, endDate: { $gte: start } }); }
async function subscriptionState(subscription) { const now = new Date(); const start = subscription.nextBillingDate || subscription.billingStartDate || now; const end = addMonths(start, 1); const free = await activeFreePeriod(subscription.schoolName, start, end); if (free) return { status: "Free", amountDue: 0, paymentRequired: false, currentBillingPeriod: { start, end }, freePeriod: free }; if (["Suspended", "Cancelled"].includes(subscription.status)) return { status: subscription.status, amountDue: subscription.monthlyFee, paymentRequired: false, currentBillingPeriod: { start, end } }; const dueEnd = new Date(start.getTime() + subscription.gracePeriodDays * 86400000); const status = now > dueEnd ? "Payment Due" : now >= start ? (subscription.gracePeriodDays ? "Grace Period" : "Payment Due") : "Due Soon"; return { status, amountDue: subscription.monthlyFee, paymentRequired: true, currentBillingPeriod: { start, end } }; }
async function createOrder(res, payment) { try { const c = await settings(); if (!c.onlineEnabled) throw Object.assign(new Error("Online payments are currently unavailable"), { status: 409 }); const order = await gateway("POST", "/v1/orders", { amount: payment.amount, currency: payment.currency, receipt: payment._id.toString(), notes: { teachhubPaymentId: payment._id.toString(), purpose: payment.purpose } }, c); payment.razorpayOrderId = order.id; payment.status = "Processing"; await payment.save(); return res.status(201).json({ paymentId: payment._id, razorpayOrderId: order.id, razorpayKeyId: c.keyId, amount: payment.amount, currency: payment.currency }); } catch (e) { await Payment.findByIdAndUpdate(payment._id, { status: "Failed" }); return fail(res, e); } }
async function finish(orderId, paymentId, signature = "") { const payment = await Payment.findOne({ razorpayOrderId: orderId }); if (!payment) throw Object.assign(new Error("Payment record not found"), { status: 404 }); if (payment.status === "Successful") return payment; if (!["Pending", "Processing"].includes(payment.status)) throw Object.assign(new Error("Payment cannot be finalized"), { status: 409 }); const c = await settings(); const remote = await gateway("GET", `/v1/payments/${encodeURIComponent(paymentId)}`, null, c); if (remote.order_id !== orderId || remote.amount !== payment.amount || remote.currency !== payment.currency || remote.status !== "captured") throw invalid("Gateway payment verification failed"); const updated = await Payment.findOneAndUpdate({ _id: payment._id, status: { $in: ["Pending", "Processing"] } }, { $set: { status: "Successful", razorpayPaymentId: paymentId, razorpaySignature: signature, transactionReference: paymentId, verifiedAt: new Date(), receiptNumber: receipt(payment) } }, { new: true }); if (!updated) return Payment.findById(payment._id); if (updated.purpose === "SCHOOL_SUBSCRIPTION") { const s = await SchoolSubscription.findOne({ schoolName: updated.schoolName }); if (s) { const start = s.nextBillingDate || s.billingStartDate || new Date(); s.nextBillingDate = addMonths(start, 1); s.currentBillingPeriod = { start, end: addMonths(start, 1) }; s.status = "Active"; await s.save(); } } return updated; }

exports.createStudentOrder = async (req, res) => { try { const student = await User.findOne({ _id: req.user.id, role: "student" }); if (!student?.schoolName) throw Object.assign(new Error("Student is not assigned to a school"), { status: 403 }); const [plan, receiver] = await Promise.all([FeePlan.findOne({ schoolName: student.schoolName, active: true }), schoolAdmin(student.schoolName)]); if (!plan || !receiver) throw Object.assign(new Error("School fee payment is not configured"), { status: 409 }); const old = await Payment.findOne({ payer: student._id, purpose: "STUDENT_SCHOOL_FEE", status: { $in: ["Pending", "Processing"] }, razorpayOrderId: { $exists: true } }).sort({ createdAt: -1 }); if (old) { const c = await settings(); return res.json({ paymentId: old._id, razorpayOrderId: old.razorpayOrderId, razorpayKeyId: c.keyId, amount: old.amount, currency: old.currency }); } return createOrder(res, await Payment.create({ payer: student._id, receiver: receiver._id, schoolName: student.schoolName, purpose: "STUDENT_SCHOOL_FEE", amount: plan.monthlyFee, currency: plan.currency, gateway: "razorpay" })); } catch (e) { fail(res, e); } };
exports.createSubscriptionOrder = async (req, res) => { try { const admin = await User.findOne({ _id: req.user.id, role: "admin" }); const subscription = await SchoolSubscription.findOne({ schoolName: admin?.schoolName }); if (!admin?.schoolName || !subscription) throw Object.assign(new Error("Subscription is not configured"), { status: 409 }); const state = await subscriptionState(subscription); if (!state.paymentRequired) return res.status(409).json({ message: state.status === "Free" ? "This school is currently in an authorized free period" : `Subscription is ${state.status}` }); const receiver = await superAdmin(); if (!receiver) throw Object.assign(new Error("Subscription receiver is not configured"), { status: 409 }); return createOrder(res, await Payment.create({ payer: admin._id, receiver: receiver._id, schoolName: admin.schoolName, purpose: "SCHOOL_SUBSCRIPTION", amount: state.amountDue, currency: subscription.currency, gateway: "razorpay", metadata: { billingPeriod: state.currentBillingPeriod } })); } catch (e) { fail(res, e); } };
exports.createTeacherSalaryOrder = async (req, res) => { try { const admin = await User.findOne({ _id: req.user.id, role: "admin" }); if (!admin?.schoolName) throw Object.assign(new Error("School administrator is not assigned"), { status: 403 }); const [teacher, pay] = await Promise.all([User.findOne({ _id: req.params.teacherId, role: "teacher", schoolName: admin.schoolName }), TeacherCompensation.findOne({ teacher: req.params.teacherId, schoolName: admin.schoolName, active: true })]); if (!teacher || !pay) throw Object.assign(new Error("Teacher salary configuration was not found"), { status: 404 }); return createOrder(res, await Payment.create({ payer: admin._id, receiver: teacher._id, schoolName: admin.schoolName, purpose: "TEACHER_SALARY", amount: pay.salary, currency: pay.currency, gateway: "razorpay", metadata: { teacher: teacher._id } })); } catch (e) { fail(res, e); } };
exports.verifyCheckout = async (req, res) => { try { const { razorpay_order_id: orderId, razorpay_payment_id: paymentId, razorpay_signature: signature } = req.body; if (!orderId || !paymentId || !signature) throw invalid("Incomplete payment verification data"); const c = await settings(); const expected = crypto.createHmac("sha256", c.keySecret).update(`${orderId}|${paymentId}`).digest("hex"); if (!same(expected, signature)) throw invalid("Payment signature verification failed"); const payment = await Payment.findOne({ razorpayOrderId: orderId, payer: req.user.id }); if (!payment) throw Object.assign(new Error("Payment does not belong to the authenticated user"), { status: 403 }); const done = await finish(orderId, paymentId, signature); res.json({ paymentId: done._id, status: done.status, receiptNumber: done.receiptNumber }); } catch (e) { fail(res, e); } };
exports.webhook = async (req, res) => { try { const secret = process.env.RAZORPAY_WEBHOOK_SECRET; if (!secret) return res.status(503).json({ message: "Webhook is not configured" }); const signature = req.headers["x-razorpay-signature"]; const expected = crypto.createHmac("sha256", secret).update(req.body).digest("hex"); if (!same(expected, signature)) return res.status(400).json({ message: "Invalid webhook signature" }); const event = JSON.parse(req.body.toString("utf8")); const eventId = String(req.headers["x-razorpay-event-id"] || crypto.createHash("sha256").update(req.body).digest("hex")); try { await PaymentWebhookEvent.create({ eventId, eventType: event.event || "unknown", razorpayOrderId: event.payload?.payment?.entity?.order_id || "" }); } catch (duplicate) { if (duplicate?.code === 11000) return res.json({ received: true, duplicate: true }); throw duplicate; } const p = event.payload?.payment?.entity; if (event.event === "payment.captured" && p?.order_id) await finish(p.order_id, p.id); if (event.event === "payment.failed" && p?.order_id) await Payment.updateOne({ razorpayOrderId: p.order_id, status: { $in: ["Pending", "Processing"] } }, { $set: { status: "Failed" } }); res.json({ received: true }); } catch (e) { console.error("Payment webhook processing failed", e.message); res.status(500).json({ message: "Webhook processing failed" }); } };
exports.createOfflineStudentRequest = async (req, res) => { try { const mode = await settings(); if (!mode.offlineEnabled) throw Object.assign(new Error("Offline payments are currently unavailable"), { status: 409 }); const method = String(req.body.method || "").toUpperCase(); if (!["CASH", "BANK_TRANSFER", "MANUAL_UPI", "CHEQUE"].includes(method)) throw invalid("A valid offline payment method is required"); const student = await User.findOne({ _id: req.user.id, role: "student" }); const [plan, receiver] = await Promise.all([FeePlan.findOne({ schoolName: student?.schoolName, active: true }), schoolAdmin(student?.schoolName)]); const reference = String(req.body.reference || "").trim(); if (!student?.schoolName || !plan || !receiver) throw Object.assign(new Error("School fee payment is not configured"), { status: 409 }); if (!reference) throw invalid("Payment reference is required"); const payment = await Payment.create({ payer: student._id, receiver: receiver._id, schoolName: student.schoolName, purpose: "STUDENT_SCHOOL_FEE", amount: plan.monthlyFee, currency: plan.currency, gateway: "offline", paymentMethod: method, status: "PendingVerification", offlineReference: reference }); res.status(201).json({ paymentId: payment._id, status: payment.status }); } catch (e) { fail(res, e); } };
exports.approveOffline = async (req, res) => { try { const payment = await Payment.findOne({ _id: req.params.id, schoolName: req.user.schoolName, gateway: "offline", status: "PendingVerification" }); if (!payment) throw Object.assign(new Error("Pending offline payment not found"), { status: 404 }); payment.status = "Successful"; payment.verifiedAt = new Date(); payment.receiptNumber = receipt(payment); await payment.save(); await audit(req, "OFFLINE_PAYMENT_APPROVED", { status: "PendingVerification" }, { schoolName: payment.schoolName, status: payment.status, paymentId: payment._id }, String(req.body.reason || "")); res.json({ paymentId: payment._id, status: payment.status, receiptNumber: payment.receiptNumber }); } catch (e) { fail(res, e); } };
exports.listPayments = async (req, res) => { try { const u = await User.findById(req.user.id); const q = u.role === "superadmin" ? {} : u.role === "admin" ? { schoolName: u.schoolName } : u.role === "teacher" ? { receiver: u._id, purpose: "TEACHER_SALARY" } : { payer: u._id }; res.json(await Payment.find(q).populate("payer receiver", "name email role").sort({ createdAt: -1 }).limit(100)); } catch (e) { fail(res, e); } };
exports.getReceipt = async (req, res) => { try { const u = await User.findById(req.user.id); const q = u.role === "superadmin" ? { _id: req.params.id } : u.role === "admin" ? { _id: req.params.id, schoolName: u.schoolName } : { _id: req.params.id, $or: [{ payer: u._id }, { receiver: u._id }] }; const p = await Payment.findOne(q).populate("payer receiver", "name email role"); if (!p || !["Successful", "Refunded", "Partially Refunded"].includes(p.status)) throw Object.assign(new Error("Receipt not found"), { status: 404 }); res.json({ receiptNumber: p.receiptNumber, payer: p.payer, receiver: p.receiver, school: p.schoolName, amount: p.amount, currency: p.currency, date: p.verifiedAt, paymentMethod: p.paymentMethod, transactionId: p.transactionReference || p.razorpayPaymentId || p.offlineReference, purpose: p.purpose, status: p.status }); } catch (e) { fail(res, e); } };
exports.getSettings = async (req, res) => { try { const c = await settings(); res.json({ gateway: "razorpay", environment: c.environment, onlineEnabled: c.onlineEnabled, offlineEnabled: c.offlineEnabled, keyId: c.keyId || "", secretConfigured: Boolean(c.keySecret) }); } catch (e) { fail(res, e); } };
exports.getPaymentOptions = async (req, res) => { try { const c = await settings(); res.json({ onlineEnabled: Boolean(c.onlineEnabled), offlineEnabled: Boolean(c.offlineEnabled), available: Boolean(c.onlineEnabled || c.offlineEnabled) }); } catch (e) { fail(res, e); } };
exports.updateSettings = async (req, res) => { try { if (!["test", "live"].includes(req.body.environment)) throw invalid("Invalid payment environment"); const onlineEnabled = req.body.onlineEnabled !== false, offlineEnabled = req.body.offlineEnabled !== false; if (!onlineEnabled && !offlineEnabled) throw invalid("At least one payment mode must be enabled"); const old = await PaymentSettings.findOne().lean(); const s = await PaymentSettings.findOneAndUpdate({}, { $set: { environment: req.body.environment, onlineEnabled, offlineEnabled, updatedBy: req.user.id } }, { new: true, upsert: true }); await audit(req, "PAYMENT_SETTINGS_CHANGED", old, s.toObject()); const c = await settings(); res.json({ gateway: s.gateway, environment: s.environment, onlineEnabled: c.onlineEnabled, offlineEnabled: c.offlineEnabled, keyId: c.keyId || "", secretConfigured: Boolean(c.keySecret) }); } catch (e) { fail(res, e); } };
exports.setFeePlan = async (req, res) => { try { const monthlyFee = Number(req.body.monthlyFee); if (!Number.isSafeInteger(monthlyFee) || monthlyFee < 1) throw invalid("Fee must be a positive integer in paise"); const old = await FeePlan.findOne({ schoolName: req.user.schoolName }).lean(); const plan = await FeePlan.findOneAndUpdate({ schoolName: req.user.schoolName }, { $set: { monthlyFee, active: req.body.active !== false, updatedBy: req.user.id } }, { new: true, upsert: true }); await audit(req, "STUDENT_FEE_CHANGED", old, plan.toObject()); res.json(plan); } catch (e) { fail(res, e); } };
exports.getFeePlan = async (req, res) => { try { res.json(await FeePlan.findOne({ schoolName: req.user.schoolName }).select("monthlyFee currency active updatedAt") || null); } catch (e) { fail(res, e); } };
exports.getMyCompensation = async (req, res) => { try { const teacher = await User.findOne({ _id: req.user.id, role: "teacher" }); if (!teacher?.schoolName) throw Object.assign(new Error("Teacher is not assigned to a school"), { status: 403 }); res.json(await TeacherCompensation.findOne({ teacher: teacher._id, schoolName: teacher.schoolName, active: true }).select("salary currency paymentCycle dueDate updatedAt") || null); } catch (e) { fail(res, e); } };
exports.listTeacherCompensations = async (req, res) => { try { res.json(await TeacherCompensation.find({ schoolName: req.user.schoolName }).populate("teacher", "name email").sort({ updatedAt: -1 })); } catch (e) { fail(res, e); } };
exports.getStudentFeePlan = async (req, res) => { try { const student = await User.findOne({ _id: req.user.id, role: "student" }); if (!student?.schoolName) throw Object.assign(new Error("Student is not assigned to a school"), { status: 403 }); res.json(await FeePlan.findOne({ schoolName: student.schoolName }).select("monthlyFee currency active updatedAt") || null); } catch (e) { fail(res, e); } };
exports.getStudentPaymentSummary = async (req, res) => { try { const student = await User.findOne({ _id: req.user.id, role: "student" }); if (!student?.schoolName) throw Object.assign(new Error("Student is not assigned to a school"), { status: 403 }); const [plan, latest] = await Promise.all([FeePlan.findOne({ schoolName: student.schoolName, active: true }).select("monthlyFee currency active updatedAt"), Payment.findOne({ payer: student._id, purpose: "STUDENT_SCHOOL_FEE" }).sort({ createdAt: -1 }).select("amount currency status verifiedAt createdAt receiptNumber")]); res.json({ currentFee: plan?.monthlyFee || 0, currency: plan?.currency || "INR", paymentAvailable: Boolean(plan?.active), paymentStatus: latest?.status || "Pending", lastPayment: latest || null, nextPayment: plan ? { amount: plan.monthlyFee, dueDate: null } : null }); } catch (e) { fail(res, e); } };
exports.setTeacherCompensation = async (req, res) => { try { const salary = Number(req.body.salary), paymentCycle = req.body.paymentCycle || "MONTHLY", dueDate = req.body.dueDate ? new Date(req.body.dueDate) : null; const teacher = await User.findOne({ _id: req.params.teacherId, role: "teacher", schoolName: req.user.schoolName }); if (!teacher || !Number.isSafeInteger(salary) || salary < 1 || !["MONTHLY", "WEEKLY", "ONE_TIME"].includes(paymentCycle) || (dueDate && Number.isNaN(+dueDate))) throw invalid("Valid teacher salary, payment cycle and due date are required"); const old = await TeacherCompensation.findOne({ teacher: teacher._id, schoolName: req.user.schoolName }).lean(); const pay = await TeacherCompensation.findOneAndUpdate({ teacher: teacher._id, schoolName: req.user.schoolName }, { $set: { salary, paymentCycle, dueDate, active: req.body.active !== false, updatedBy: req.user.id } }, { new: true, upsert: true }); await audit(req, "TEACHER_SALARY_CHANGED", old, pay.toObject()); res.json(pay); } catch (e) { fail(res, e); } };
exports.setSubscription = async (req, res) => { try { const schoolName = String(req.params.schoolName || "").trim(), monthlyFee = Number(req.body.monthlyFee), gracePeriodDays = Number(req.body.gracePeriodDays || 0); if (!schoolName || !Number.isSafeInteger(monthlyFee) || monthlyFee < 1 || !Number.isInteger(gracePeriodDays) || gracePeriodDays < 0 || gracePeriodDays > 90) throw invalid("Valid school, monthly fee and grace period are required"); const old = await SchoolSubscription.findOne({ schoolName }).lean(); const billingStartDate = req.body.billingStartDate ? new Date(req.body.billingStartDate) : old?.billingStartDate || new Date(); if (Number.isNaN(+billingStartDate)) throw invalid("Invalid billing start date"); const sub = await SchoolSubscription.findOneAndUpdate({ schoolName }, { $set: { monthlyFee, billingStartDate, nextBillingDate: old?.nextBillingDate || billingStartDate, gracePeriodDays, status: req.body.status === "Suspended" ? "Suspended" : "Payment Due", updatedBy: req.user.id } }, { new: true, upsert: true }); await audit(req, "SUBSCRIPTION_CHANGED", old, sub.toObject()); res.json({ subscription: sub, billing: await subscriptionState(sub) }); } catch (e) { fail(res, e); } };
exports.changeSubscriptionStatus = async (req, res) => { try { const status = String(req.body.status || ""); if (!["Suspended", "Cancelled", "Payment Due", "Active"].includes(status)) throw invalid("Invalid subscription status"); const sub = await SchoolSubscription.findOne({ schoolName: req.params.schoolName }); if (!sub) throw Object.assign(new Error("Subscription not found"), { status: 404 }); const previous = sub.toObject(); sub.status = status; sub.updatedBy = req.user.id; await sub.save(); await audit(req, status === "Suspended" ? "SUBSCRIPTION_SUSPENDED" : status === "Active" ? "SUBSCRIPTION_REACTIVATED" : "SUBSCRIPTION_STATUS_CHANGED", previous, sub.toObject(), String(req.body.reason || "")); res.json({ subscription: sub, billing: await subscriptionState(sub) }); } catch (e) { fail(res, e); } };
exports.grantFreePeriod = async (req, res) => { try { const startDate = new Date(req.body.startDate || Date.now()), endDate = new Date(req.body.endDate || (Date.now() + Number(req.body.days || 0) * 86400000)); if (Number.isNaN(+startDate) || Number.isNaN(+endDate) || endDate < startDate) throw invalid("A valid free-period start and end date are required"); const subscription = await SchoolSubscription.findOne({ schoolName: req.params.schoolName }); if (!subscription) throw Object.assign(new Error("Subscription not found"), { status: 404 }); const period = await FreePeriod.create({ schoolName: subscription.schoolName, type: req.body.type || "OTHER", startDate, endDate, reason: String(req.body.reason || ""), note: String(req.body.note || ""), grantedBy: req.user.id }); await audit(req, "FREE_PERIOD_GRANTED", null, period.toObject(), period.reason); res.status(201).json(period); } catch (e) { fail(res, e); } };
exports.cancelFreePeriod = async (req, res) => { try { const period = await FreePeriod.findOne({ _id: req.params.id, status: "Active" }); if (!period) throw Object.assign(new Error("Active free period not found"), { status: 404 }); period.status = "Cancelled"; period.cancelledAt = new Date(); period.cancelledBy = req.user.id; await period.save(); await audit(req, "FREE_PERIOD_CANCELLED", { schoolName: period.schoolName, status: "Active" }, period.toObject(), String(req.body.reason || "")); res.json(period); } catch (e) { fail(res, e); } };
exports.getSubscriptionStatus = async (req, res) => { try { const admin = await User.findOne({ _id: req.user.id, role: "admin" }); const s = await SchoolSubscription.findOne({ schoolName: admin?.schoolName }); if (!s) throw Object.assign(new Error("Subscription is not configured"), { status: 404 }); res.json({ subscription: s, billing: await subscriptionState(s) }); } catch (e) { fail(res, e); } };
exports.listSubscriptions = async (req, res) => { try { const subscriptions = await SchoolSubscription.find().sort({ schoolName: 1 }).lean(); const result = await Promise.all(subscriptions.map(async subscription => ({ subscription, billing: await subscriptionState(subscription), freePeriods: await FreePeriod.find({ schoolName: subscription.schoolName }).sort({ startDate: -1 }).limit(20).lean() }))); res.json(result); } catch (e) { fail(res, e); } };
exports.listAuditLogs = async (req, res) => { try { res.json(await PaymentAuditLog.find().populate("actor", "name email role").sort({ createdAt: -1 }).limit(200)); } catch (e) { fail(res, e); } };
exports.refundPayment = async (req, res) => { try { const payment = await Payment.findById(req.params.id); const amount = Number(req.body.amount); if (!payment || !["Successful", "Partially Refunded"].includes(payment.status) || !payment.razorpayPaymentId) throw Object.assign(new Error("Only refundable online payments can be refunded"), { status: 404 }); const alreadyRefunded = payment.refunds.reduce((sum, item) => sum + item.amount, 0); if (!Number.isSafeInteger(amount) || amount < 1 || amount > payment.amount - alreadyRefunded) throw invalid("Invalid refund amount"); const c = await settings(); const refund = await gateway("POST", `/v1/payments/${encodeURIComponent(payment.razorpayPaymentId)}/refund`, { amount, notes: { reason: String(req.body.reason || "") } }, c); payment.refunds.push({ refundId: refund.id, amount, reason: String(req.body.reason || ""), refundedAt: new Date(), initiatedBy: req.user.id }); const total = payment.refunds.reduce((sum, item) => sum + item.amount, 0); payment.status = total >= payment.amount ? "Refunded" : "Partially Refunded"; await payment.save(); await audit(req, "REFUND_INITIATED", { schoolName: payment.schoolName, status: "Successful" }, { schoolName: payment.schoolName, status: payment.status, paymentId: payment._id, amount }, String(req.body.reason || "")); res.json({ paymentId: payment._id, status: payment.status, refundId: refund.id }); } catch (e) { fail(res, e); } };
exports.dashboard = async (req, res) => { try { const u = await User.findById(req.user.id); const q = u.role === "superadmin" ? {} : u.role === "admin" ? { schoolName: u.schoolName } : u.role === "teacher" ? { receiver: u._id } : { payer: u._id }; const payments = await Payment.find(q).sort({ createdAt: -1 }).limit(100); const successful = payments.filter(p => p.status === "Successful"); res.json({ totalReceived: successful.reduce((sum, p) => sum + p.amount, 0), pendingPayments: payments.filter(p => ["Pending", "Processing", "PendingVerification"].includes(p.status)).length, paymentCount: payments.length, recentPayments: payments.slice(0, 10) }); } catch (e) { fail(res, e); } };
