const router = require("express").Router();
const { protect, authorize } = require("../middleware/authMiddleware");
const feature = require("../controllers/featureController");
router.use(protect);
router.post("/groups", authorize("teacher"), feature.createGroup);
router.get("/groups", authorize("teacher", "student"), feature.getGroups);
router.get("/groups/:id/messages", authorize("teacher", "student"), feature.getGroupMessages);
router.post("/groups/:id/messages", authorize("teacher", "student"), feature.sendGroupMessage);
router.post("/teacher-leaves", authorize("teacher"), feature.createLeave);
router.get("/teacher-leaves", authorize("teacher", "admin"), feature.getLeaves);
router.put("/teacher-leaves/:id", authorize("admin"), feature.reviewLeave);
router.get("/teacher-leaves/active/list", authorize("student", "teacher", "admin"), feature.getActiveLeaves);
router.post("/appointments", feature.createAppointment);
router.get("/appointments", feature.getAppointments);
router.put("/appointments/:id", feature.updateAppointment);
router.post("/timetable", authorize("admin"), feature.createTimetable);
router.get("/timetable", authorize("admin", "teacher", "student"), feature.getTimetable);
router.delete("/timetable/:id", authorize("admin"), feature.deleteTimetable);
module.exports = router;
