const router = require("express").Router();
const { protect, authorize } = require("../middleware/authMiddleware");
const feature = require("../controllers/featureController");
router.use(protect);
router.post("/groups", authorize("teacher"), feature.createGroup);
router.get("/groups", authorize("teacher", "student"), feature.getGroups);
router.get("/groups/:id", authorize("teacher", "student"), feature.getGroup);
router.get("/groups/:id/messages", authorize("teacher", "student"), feature.getGroupMessages);
router.post("/groups/:id/messages", authorize("teacher", "student"), feature.sendGroupMessage);
router.post("/teacher-leaves", authorize("teacher"), feature.createLeave);
router.get("/teacher-leaves", authorize("teacher", "admin"), feature.getLeaves);
router.put("/teacher-leaves/:id", authorize("admin"), feature.reviewLeave);
router.put("/teacher-leaves/:id/approve", authorize("admin"), (req, res) => { req.body.status = "Approved"; return feature.reviewLeave(req, res); });
router.put("/teacher-leaves/:id/reject", authorize("admin"), (req, res) => { req.body.status = "Rejected"; return feature.reviewLeave(req, res); });
router.get("/teacher-leaves/active/list", authorize("student", "teacher", "admin"), feature.getActiveLeaves);
router.post("/appointments", authorize("unassigned", "student", "teacher"), feature.createAppointment);
router.get("/appointments", authorize("admin", "unassigned", "student", "teacher"), feature.getAppointments);
router.put("/appointments/:id", authorize("admin", "unassigned", "student", "teacher"), feature.updateAppointment);
router.post("/timetable", authorize("admin"), feature.createTimetable);
router.put("/timetable/:id", authorize("admin"), feature.updateTimetable);
router.get("/timetable", authorize("admin", "teacher", "student"), feature.getTimetable);
router.put("/teacher-attendance/today", authorize("teacher"), feature.markTeacherAttendance);
router.delete("/timetable/:id", authorize("admin"), feature.deleteTimetable);
module.exports = router;
