const router = require("express").Router();
const { protect, authorize } = require("../middleware/authMiddleware");
const payment = require("../controllers/paymentController");

router.post("/student-payments/create-order", protect, authorize("student"), payment.createStudentOrder);
router.post("/student-payments/cancel-processing", protect, authorize("student"), payment.cancelProcessingPayment);
router.post("/student-payments/offline-request", protect, authorize("student"), payment.createOfflineStudentRequest);
router.get("/student-payments/fee-plan", protect, authorize("student"), payment.getStudentFeePlan);
router.get("/student-payments/summary", protect, authorize("student"), payment.getStudentPaymentSummary);
router.get("/student-payments/dashboard", protect, authorize("student"), payment.getStudentDashboard);
router.post("/school-subscription/create-order", protect, authorize("admin"), payment.createSubscriptionOrder);
router.post("/teacher-payments/:teacherId/create-order", protect, authorize("admin"), payment.createTeacherSalaryOrder);
router.post("/payments/verify-checkout", protect, payment.verifyCheckout);
router.get("/payments", protect, payment.listPayments);
router.get("/payments/dashboard", protect, payment.dashboard);
router.get("/payment-options", protect, payment.getPaymentOptions);
router.post("/payments/:id/verify-status", protect, payment.verifyPaymentStatusDirectly);
router.get("/payments/:id/receipt", protect, payment.getReceipt);
router.put("/payments/:id/approve-offline", protect, authorize("admin"), payment.approveOffline);
router.put("/payments/:id/reject-offline", protect, authorize("admin"), payment.rejectOffline);
router.post("/payments/:id/refund", protect, authorize("superadmin"), payment.refundPayment);
router.get("/payment-settings", protect, authorize("superadmin", "admin", "teacher"), payment.getSettings);
router.put("/payment-settings", protect, authorize("superadmin", "admin", "teacher"), payment.updateSettings);
router.get("/admin/fee-plan", protect, authorize("admin"), payment.getFeePlan);
router.put("/admin/fee-plan", protect, authorize("admin"), payment.setFeePlan);
router.post("/admin/student-payments/:studentId/mark-paid", protect, authorize("admin"), payment.markStudentFeePaidDirectly);
router.get("/admin/teacher-compensations", protect, authorize("admin"), payment.listTeacherCompensations);
router.put("/admin/teacher-compensations/:teacherId", protect, authorize("admin"), payment.setTeacherCompensation);
router.post("/admin/teacher-payments/:teacherId/offline-request", protect, authorize("admin"), payment.createOfflineTeacherRequest);
router.get("/teacher/my-compensation", protect, authorize("teacher"), payment.getMyCompensation);
router.put("/superadmin/subscriptions/:schoolName", protect, authorize("superadmin"), payment.setSubscription);
router.put("/superadmin/subscriptions/:schoolName/status", protect, authorize("superadmin"), payment.changeSubscriptionStatus);
router.get("/superadmin/subscriptions", protect, authorize("superadmin"), payment.listSubscriptions);
router.post("/superadmin/subscriptions/:schoolName/free-period", protect, authorize("superadmin"), payment.grantFreePeriod);
router.put("/superadmin/free-periods/:id/cancel", protect, authorize("superadmin"), payment.cancelFreePeriod);
router.get("/superadmin/payment-audit-logs", protect, authorize("superadmin"), payment.listAuditLogs);
router.get("/admin/subscription", protect, authorize("admin"), payment.getSubscriptionStatus);
module.exports = router;
